In [1]:
import pandas as pd
import numpy as np
import timeit
from kernel_fca_oo import FreqLexiSeriateSystem, ConfLexiSeriateSystem, FCASystemDF, KMeansSystem
from IPython.display import display, HTML

In [2]:

#data = pd.read_csv(KATALOOG+"cmp-bin-grocery.csv", sep=',', index_col=0, encoding='latin1')

In [3]:
c_i = range(0, 12)
KATALOOG = "..\\"

fns = ["cmp-bin-iapb09.csv",
       "cmp-bin-STT_majandus.csv",
       "cmp-bin-TTTH_kardlaga.csv",
       "cmp-bin-grocery.csv", 
       "cmp-bin-ecommerce-sampled.csv", 
       "cmp-bin-house-votes-84.csv",
       "cmp-bin-instacart-600-sample.csv",
       "cmp-bin-student-gradings.csv"]

for fn in fns:
    print("\nFile:", fn)
    data = pd.read_csv(KATALOOG+fn, sep=',', index_col=0, encoding='latin1')
    result_df = pd.DataFrame(columns = ["time"] + ["c"+str(i) for i in c_i])
    #systems = {"MS": FCASystemDF(data), "FL": FreqLexiSeriateSystem(data)}
    systems = {#"MS": FCASystemDF(data), 
        "CL": ConfLexiSeriateSystem(data), 
        "FL": FreqLexiSeriateSystem(data),
        "CLr": ConfLexiSeriateSystem(data, refill=True),
        "FLr": FreqLexiSeriateSystem(data, refill=True)}
    #for i in range(2, 13, 2):
    #    systems["KM"+str(i)] = KMeansSystem(data, n_chains=i)
    for s_name, system in systems.items():
        start = timeit.default_timer()
        _, uc =  system.conceptchaincover(max_cc=12)
        time = timeit.default_timer() - start
        if len(uc) < len(c_i):
            uc += [np.nan] * (len(c_i) - len(uc))  
        result_df.loc[s_name] = [time] + uc[:len(c_i)]
    #[uc for (_, uc) in zip(system.conceptchaincover())]
    display(result_df)
    result_df.to_csv(path_or_buf=KATALOOG+"res-"+fn)

File: cmp-bin-iapb09.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,0.395699,0.256524,0.195941,0.178086,0.160232,0.146956,0.134900,0.119945,0.109873,0.100565,0.092172,NaN,NaN
FL,0.519987,0.288418,0.247368,0.233481,0.176255,0.156875,0.147566,0.130780,0.123455,0.119182,0.114604,0.103617,0.096139
CLr,0.364623,0.256524,0.235617,0.224020,0.201129,0.178392,0.171372,0.166946,0.162216,0.146498,0.134442,0.128796,0.108500
FLr,0.373682,0.288418,0.278498,0.243400,0.234396,0.214406,0.200824,0.193652,0.144361,0.133984,0.121929,0.110331,0.105906

File: cmp-bin-STT_majandus.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,1.628569,0.474560,0.449603,0.441091,0.416328,0.362159,0.327336,0.303540,0.285355,0.277036,0.254982,0.243374,0.221513
FL,1.668066,0.472432,0.409750,0.374154,0.359644,0.345328,0.331012,0.319791,0.268524,0.258851,0.239505,0.232347,0.220352
CLr,1.677218,0.474560,0.449603,0.441091,0.416328,0.362159,0.327336,0.298897,0.280712,0.268717,0.261559,0.244728,0.223447
FLr,1.784906,0.472432,0.417295,0.403947,0.362739,0.348036,0.333333,0.324821,0.313600,0.305668,0.299091,0.285162,0.281486

File: cmp-bin-TTTH_kardlaga.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,0.670420,0.506842,0.416624,0.384187,0.342625,0.289914,0.253928,0.231627,0.204764,0.188545,0.181956,0.165737,0.153573
FL,0.671591,0.506842,0.446021,0.411049,0.393310,0.366954,0.343132,0.332489,0.314749,0.304612,0.238723,0.212874,0.205271
CLr,0.676177,0.506842,0.427268,0.395844,0.335023,0.313229,0.285352,0.232641,0.212874,0.198175,0.191080,0.182463,0.177395
FLr,0.634336,0.506842,0.446021,0.411049,0.393310,0.366954,0.343132,0.331982,0.315256,0.303599,0.291941,0.284845,0.279270

File: cmp-bin-grocery.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,0.239258,0.828431,0.759804,0.710784,0.647059,0.602941,0.568627,0.534314,0.497549,0.463235,0.428922,0.404412,0.379902
FL,0.214515,0.828431,0.767157,0.703431,0.639706,0.580882,0.546569,0.512255,0.487745,0.455882,0.436275,0.409314,0.375000
CLr,0.232760,0.828431,0.759804,0.710784,0.669118,0.625000,0.573529,0.522059,0.500000,0.450980,0.406863,0.370098,0.348039
FLr,0.216093,0.828431,0.767157,0.742647,0.678922,0.661765,0.627451,0.571078,0.534314,0.500000,0.477941,0.470588,0.450980

File: cmp-bin-ecommerce-sampled.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,1.147873,0.891988,0.812306,0.771138,0.727313,0.691899,0.649845,0.620629,0.584329,0.557769,0.528552,0.500221,0.470120
FL,1.138293,0.891988,0.812306,0.766711,0.727756,0.689243,0.653829,0.621514,0.589641,0.560425,0.532537,0.502435,0.471890
CLr,1.239885,0.891988,0.812306,0.771138,0.737052,0.695883,0.652058,0.621071,0.590084,0.555998,0.528110,0.498451,0.471005
FLr,1.246014,0.891988,0.812306,0.766711,0.727756,0.689243,0.653829,0.621514,0.589641,0.560425,0.532537,0.502435,0.471890

File: cmp-bin-house-votes-84.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,0.311881,0.831950,0.728734,0.622925,0.446317,0.312500,0.264004,0.200207,0.160010,0.129668,0.100104,0.078320,NaN
FL,0.330924,0.831172,0.696836,0.622407,0.526712,0.451763,0.396006,0.306535,0.260633,0.219917,0.186463,0.143154,0.096214
CLr,0.269324,0.831950,0.727178,0.581691,0.455913,0.436203,0.421162,0.392635,0.318983,0.296940,0.259336,0.225622,0.216286
FLr,0.299468,0.831172,0.696836,0.684647,0.616442,0.546421,0.492479,0.378371,0.272044,0.266598,0.208247,0.174533,0.165197

File: cmp-bin-instacart-600-sample.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,1.292404,0.836632,0.796211,0.762316,0.730316,0.700632,0.678947,0.655368,0.633895,0.610947,0.593263,0.576000,0.557263
FL,1.148531,0.837895,0.796632,0.759789,0.727158,0.697684,0.672211,0.646737,0.625684,0.606105,0.586316,0.570105,0.551579
CLr,1.045563,0.836632,0.792632,0.765474,0.741053,0.720000,0.696000,0.680632,0.650737,0.629263,0.614316,0.599789,0.575579
FLr,1.125932,0.837895,0.795579,0.761895,0.733053,0.709684,0.688000,0.666737,0.662737,0.629053,0.607158,0.591789,0.574526

File: cmp-bin-student-gradings.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CL,0.369317,0.600918,0.490050,0.424229,0.357752,0.308550,0.268751,0.229827,0.196807,0.166193,0.140171,0.119615,0.097748
FL,0.349164,0.600918,0.504264,0.437787,0.376558,0.317516,0.273125,0.235950,0.202930,0.176689,0.155040,0.133173,0.111305
CLr,0.260150,0.600918,0.562650,0.522852,0.497923,0.397988,0.332167,0.281435,0.247321,0.229390,0.199869,0.178001,0.163569
FLr,0.221479,0.600918,0.562213,0.522414,0.506014,0.476055,0.464465,0.419418,0.395801,0.374153,0.366062,0.317297,0.295430

In [4]:
4000*0.625

2500.0