In [9]:
import pandas as pd
import numpy as np
import timeit
from kernel_fca_oo import LexiSystem, LexiTSystem
from IPython.display import display

In [10]:
c_i = range(0, 12)
KATALOOG = "..\\"

fns = ["cmp-bin-zoo.csv",
       "cmp-bin-house-votes-84.csv",
       "cmp-bin-student-gradings.csv"]

for fn in fns:
    print("\nFile:", fn)
    data = pd.read_csv(KATALOOG+fn, sep=',', index_col=0, encoding='latin1')
    result_df = pd.DataFrame(columns = ["time"] + ["c"+str(i) for i in c_i])
    systems = {"CLFT": LexiTSystem(data, transform="CL", full_lexi=True),
               "FLFT": LexiTSystem(data, transform="FL", full_lexi=True),
               "CLF": LexiSystem(data, transform="CL", full_lexi=True),
               "FLF": LexiSystem(data, transform="FL", full_lexi=True),
               "CL": LexiSystem(data, transform="CL", full_lexi=False),  # Probably simplest and best version
               "FL": LexiSystem(data, transform="FL", full_lexi=False),
               "CLT": LexiTSystem(data, transform="CL", full_lexi=False),
               "FLT": LexiTSystem(data, transform="FL", full_lexi=False)}
    ones = data.sum().sum()
    for s_name, system in systems.items():
        start = timeit.default_timer()
        _, uc =  system.conceptchaincover(uncovered=0.1, max_cc=20)
        time = timeit.default_timer() - start
        if len(uc) < len(c_i):
            uc += [np.nan] * (len(c_i) - len(uc))  
        result_df.loc[s_name] = [time] + uc[:len(c_i)]
    display(result_df)
    result_df.to_csv(path_or_buf=KATALOOG+"res-"+fn)

File: cmp-bin-zoo.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CLFT,0.256762,0.574242,0.413636,0.243939,0.159091,0.095455,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLFT,0.272531,0.581818,0.445455,0.240909,0.137879,0.072727,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CLF,0.107845,0.574242,0.443939,0.225758,0.153030,0.096970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLF,0.130684,0.581818,0.445455,0.240909,0.166667,0.127273,0.077273,NaN,NaN,NaN,NaN,NaN,NaN
CL,0.091138,0.574242,0.443939,0.225758,0.154545,0.098485,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FL,0.104626,0.581818,0.445455,0.240909,0.168182,0.128788,0.081818,NaN,NaN,NaN,NaN,NaN,NaN
CLT,0.211374,0.574242,0.413636,0.243939,0.171212,0.095455,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLT,0.222457,0.581818,0.445455,0.240909,0.137879,0.072727,NaN,NaN,NaN,NaN,NaN,NaN,NaN

File: cmp-bin-house-votes-84.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CLFT,0.675990,0.831950,0.727956,0.588434,0.394191,0.228994,0.158454,0.119813,0.070021,NaN,NaN,NaN,NaN
FLFT,0.807153,0.831172,0.696836,0.616701,0.508817,0.417531,0.354512,0.264782,0.206172,0.157158,0.067687,NaN,NaN
CLF,0.342124,0.831950,0.727956,0.604253,0.403268,0.250000,0.202541,0.168050,0.111515,0.066131,NaN,NaN,NaN
FLF,0.417641,0.831172,0.696836,0.621110,0.511411,0.438019,0.380965,0.277490,0.233921,0.192168,0.104512,0.047459,NaN
CL,0.286109,0.831950,0.727956,0.579876,0.364627,0.240664,0.182054,0.148859,0.107365,0.074170,NaN,NaN,NaN
FL,0.322501,0.831172,0.696836,0.621110,0.511929,0.439834,0.382521,0.279046,0.238589,0.195539,0.129927,0.091546,NaN
CLT,0.583061,0.831950,0.727956,0.579876,0.364627,0.240664,0.182054,0.139782,0.098029,NaN,NaN,NaN,NaN
FLT,0.599916,0.831172,0.696836,0.616701,0.509077,0.419087,0.356587,0.267894,0.209544,0.074170,NaN,NaN,NaN

File: cmp-bin-student-gradings.csv

,time,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
CLFT,1.017006,0.600918,0.489613,0.401050,0.332167,0.276405,0.226328,0.177345,0.144107,0.109556,0.089438,NaN,NaN
FLFT,0.998783,0.600918,0.494642,0.416138,0.342445,0.288651,0.223923,0.182375,0.141701,0.113492,0.087907,NaN,NaN
CLF,0.478173,0.600918,0.489613,0.419856,0.346162,0.278592,0.235513,0.199869,0.159414,0.122895,0.102340,0.081128,NaN
FLF,0.478041,0.600918,0.494642,0.416138,0.342445,0.288869,0.244697,0.196807,0.159195,0.132298,0.099060,NaN,NaN
CL,0.343818,0.600918,0.489613,0.419856,0.347037,0.280997,0.239449,0.200087,0.161382,0.134704,0.108244,0.085939,NaN
FL,0.349715,0.600918,0.494642,0.419200,0.356440,0.295648,0.232889,0.204024,0.172316,0.143669,0.117647,0.091406,NaN
CLT,0.743345,0.600918,0.489613,0.401050,0.333042,0.277717,0.228953,0.180625,0.141920,0.116554,0.095124,NaN,NaN
FLT,0.798187,0.600918,0.494642,0.419200,0.356440,0.295648,0.232889,0.180625,0.149792,0.120271,0.099060,NaN,NaN